### ISSUE TITLE
Confused dialect vs language

### ISSUE THREAD

**Issue by meling** [cgnieder/translations#19] opened 2021-12-16 19:53 UTC
I do this in my `.sty` file:
```latex
\RequirePackage{translations}

\DeclareTranslationFallback{master}{Master Thesis}
\DeclareTranslation{English}{master}{Master Thesis}
\DeclareTranslation{Norsk}{master}{Masteroppgave}
\DeclareTranslation{Nynorsk}{master}{Masteroppgåve}
...
\def\bachelor{\GetTranslation{bachelor}}
\def\master{\GetTranslation{master}}
\def\phd{\GetTranslation{phd}}
...
\def\VK@thesistype{}
\def\thesistype#1{\def\VK@thesistype{#1}}
...
\textsf{\VK@mainfontsize{\VK@thesistype{} - \VK@date}}
```
But no matter which of `norsk` and `nynorsk` I use in:

```latex
\documentclass[12pt,norsk]{report}
\usepackage[norsk]{babel}
\thesistype{\master}
```

- The `\GetTranslation` seems to always pick the `nynorsk` variant: `Masteroppgåve`. 
- If I remove the `nynorsk` translation, it picks the `norsk` variant: `Masteroppgave`, as expected.
- If I use `english` or `american` in the documentclass it picks the `Master Thesis` variant, as expected.

What am I missing? Any assistance would be greately appreciated.

**Comment by cgnieder** [comment] 2022-01-04 12:24
I think the problem is that `nynorsk` was defined as an alias to `norsk` and not as a dialect. This is now fixed.

**Closed as completed by cgnieder** 2022-01-04 12:24 UTC
