### ISSUE TITLE
Add a link to the github page to the documentation

### ISSUE THREAD

**Issue by paternal** [cgnieder/translations#3] opened 2017-04-17 13:35 UTC
There is no link to this github project in the documentation. And since the home page is down (#2), the only option remaining to ask a question or report a bug is to send a private email. (I only found this page by chance, after having sent an email for another question).

**Comment by cgnieder** [comment] 2017-04-18 07:25
This is essentially a duplicate of issue #2 ;)

**Closed as completed by cgnieder** 2017-04-18 07:25 UTC
Labels: duplicate
